In [1]:
pip install-U scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:


# Load dataset
df_iris = pd.read_csv('iris.csv')

# Adjust column names based on the actual names
x = df_iris[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
y = df_iris['variety']  # Adjusted to the correct column name for species

# Train-test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

# SVM model
svm_model = SVC(kernel='rbf')
svm_model.fit(x_train, y_train)
svm_pred = svm_model.predict(x_test)

# Model evaluation
print("Confusion Matrix:")
print(confusion_matrix(y_test, svm_pred))
print("Classification Report:")
print(classification_report(y_test, svm_pred))

# Single prediction
print("Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4):")
predicted_species = svm_model.predict([[4.4, 4.4, 4.4, 4.4]])
print(predicted_species)


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        19
  Versicolor       1.00      1.00      1.00        13
   Virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Predict the flower type for data Sepal (4.4, 4.4) and Petal (4.4, 4.4):
['Virginica']


/Users/krethik/miniconda3/envs/qiskit/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [4]:
import pandas as pd

In [5]:
df_iris = pd.read_csv('iris.csv')
print(df_iris.columns)

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')
